services:
  fastapi:
    container_name: fastapi
    build: ..
    command: uvicorn --factory api.app:create_app --reload --port 8000 --host 0.0.0.0
    ports:
      - '8000:8000'
    volumes:
      - ..:/code
    networks:
      - backend
    restart: always

networks:
  backend:
    driver: bridge