[tool.poetry]
name = "bookflix"
version = "0.1.0"
description = ""
authors = ["zmskv <zmskvxd@gmail.com>, khnychenkoav <khnartem@gmail.com>, malmax5 <malmax5@mail.ru>, milkyway <mihateren2003@gmail.com>, aazaretskaya <nastya.zaretskaya.1995@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
fastapi = "^0.110.0"
uvicorn = "^0.29.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
