"""add is_preferences

Revision ID: 42f37a8c8eb6
Revises: f20f304b1379
Create Date: 2024-05-14 21:30:43.536491

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '42f37a8c8eb6'
down_revision: Union[str, None] = 'f20f304b1379'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('is_preferences', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'is_preferences')
    # ### end Alembic commands ###
