# pylint: disable=no-member
from typing import Sequence, Union
import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision: str = 'eccbd7262111'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('role',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('name', sa.String(), nullable=False),
                    sa.Column('permissions', sa.JSON(), nullable=True),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('user_history',
                    sa.Column('id', sa.UUID(), nullable=False),
                    sa.Column('liked_books', sa.JSON(), nullable=True),
                    sa.Column('liked_films', sa.JSON(), nullable=True),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('user_views',
                    sa.Column('id', sa.UUID(), nullable=False),
                    sa.Column('liked_books', sa.ARRAY(sa.String()), nullable=True),
                    sa.Column('liked_films', sa.ARRAY(sa.String()), nullable=True),
                    sa.Column('disliked_books', sa.ARRAY(sa.String()), nullable=True),
                    sa.Column('disliked_films', sa.ARRAY(sa.String()), nullable=True),
                    sa.Column('favorite_genre_books', sa.String(), nullable=False),
                    sa.Column('favorite_genre_films', sa.String(), nullable=False),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('user',
                    sa.Column('id', sa.UUID(), nullable=False),
                    sa.Column('email', sa.String(), nullable=False),
                    sa.Column('username', sa.String(), nullable=False),
                    sa.Column('registered_at', sa.TIMESTAMP(), nullable=True),
                    sa.Column('role_id', sa.Integer(), nullable=True),
                    sa.Column('hashed_password', sa.String(), nullable=False),
                    sa.Column('is_active', sa.Boolean(), nullable=False),
                    sa.Column('is_superuser', sa.Boolean(), nullable=False),
                    sa.Column('is_verified', sa.Boolean(), nullable=False),
                    sa.ForeignKeyConstraint(['role_id'], ['role.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    op.drop_table('user_views')
    op.drop_table('user_history')
    op.drop_table('role')
    # ### end Alembic commands ###
